//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_event
    {
        public int ID_activity { get; set; }
        public int ID_event { get; set; }
        public int day { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<int> ID_uzer { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Event Event { get; set; }
        public virtual Uzer Uzer { get; set; }
    }
}
