//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzer_role
    {
        public int Id { get; set; }
        public int ID_uzer { get; set; }
        public int ID_role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Uzer Uzer { get; set; }
    }
}
